### PR TITLE
Update the elb_subnets tags to match kops v1.8.0 format

### PR DESCRIPTION
**Pull request by KashifSaadat**

### CODE REVIEW

**Comment by gambol99** [comment]
what does this do???

**Comment by KashifSaadat** [comment]
Nothing, kops v1.8.0 changed the tag format slightly for the elb subnets, so you end up with the following invalid terraform change:
```
  ~ module.infra.aws_subnet.elb_subnets[0]
      tags.kubernetes.io/role/elb: "1" => "true"

  ~ module.infra.aws_subnet.elb_subnets[1]
      tags.kubernetes.io/role/elb: "1" => "true"
```

**Comment by gambol99** [comment]
https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/aws/aws.go#L3018-L3034 ... only appears to check for existence

**Comment by gambol99** [comment]
i didn't think kops tagged subnets with ELB's tags ... hmm ... ok .. i'm gonna LG as i trust you

**Review by gambol99 — APPROVED** [review]

**Pull request merged**
